### ISSUE TITLE
Component - Sidebar

### ISSUE THREAD

**Issue by johnotu** [BuildForSDGCohort2/Team-023-Frontend#14]
Create a Sidebar component for displaying Sections and Filters.

 The component files (_index.js_, _test.js_, etc) should be housed inside a folder named after the component for example:

```
- components/
--- Sidebar/
----- index.js
----- test.js
```

![Sidebar](https://user-images.githubusercontent.com/11388011/92047030-f37c6e80-ed7b-11ea-937b-d40804dba36d.png)

[Dashboard template](https://github.com/StartBootstrap/startbootstrap-sb-admin-2)

**Comment by Abuh05** [comment]
Please anyone working on this?

**Comment by toby-adedipe** [comment]
@Abuh05 I don't think anyone is working on it, if they are, they would have assigned it to themselves, I'm going to pick another one and leave this one for you though
