### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by johnotu** [BuildForSDGCohort2/Team-023-Frontend#2]
Create user stories for 
- microfinance and loans service providers and 
- their customers. 

The stories should cover the minimum value that this first version should offer as defined by the MVP

**Comment by Abuh05** [comment]
Great! The MVP please?

**Comment by johnotu** [comment]
We're waiting on you and Busayo for that. 

Noticed our project isn't visible on the cohort Github Org because of the way it was created. Coordinating with Cliff to have a new one and get the already submitted URL changed.

Please go ahead with the prototypes based on the user stories created.

**Comment by Abuh05** [comment]
Okay! I contacted Busayo today. 

We will be meeting tomorrow to discuss further. 

We will give in our Best!

**Comment by baldcodr** [comment]
Hi guys. Pls how do I join the team on slack?
